# Generated by Django 6.1.1 on 2026-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
