# Generated by Django 6.1.1 on 2026-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='llm_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_platform',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
